config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#home'
  get '/users/show_race_type'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#logout'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  resources :users do 
    resources :friendships, only: [:create, :show]
  end
  resources :friendships, only: [:update]
  resources :statistics, only: [:destroy] do 
      resources :likes, only: [:create]
    end
  resources :likes, only: [:update]
  resources :races, except: [:destroy] do
    resources :statistics, only: [:new, :create, :index, :edit, :update] 
  end
  resources :types do 
    resources :statistics, only: [:index]
  end
  get "/types/:slug_races", to: 'types#show_races'
end

app/models/statistic.rb
class Statistic < ApplicationRecord
    belongs_to :user
    belongs_to :race
    has_many :likes, -> { where(likes: {like: true } ) }
    validates :finish_time, presence: true
    validates :finish_pace, presence: true

    scope :ordered, -> do
        order(finish_time: :asc)
    end

    def finish_time_format
        self.finish_time.strftime("%H:%M:%S")
    end

    def finish_pace_format
        self.finish_pace.strftime("%H:%M")
    end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :require_logged_in, only: [:new, :create, :edit, :update, :destroy]
  def new
    if params[:race_id]
      @race = Race.find(params[:race_id])
      @statistic = @race.statistics.build
    end
  end

  def create
    race = Race.find(params[:race_id])
    stat = race.statistics.build 
    stat.update(stat_params)
    stat.user = current_user
    stat.save
    redirect_to race_statistics_path(race)
  end

  def index
    @race = Race.find(params[:race_id])
    @public_stats = @race.public_statistics(current_user)

    if params[:sort]
      if params[:sort] === "name"
        @public_stats = @public_stats.sort{|a, b| a.user.last_name <=> b.user.last_name}
        @race
      elsif params[:sort] === "finish_time"
        @public_stats = @public_stats.sort{|a, b| a.finish_time_format <=> b.finish_time_format}
        @race
      elsif params[:sort] === "likes"
        @public_stats = @public_stats.sort{|a, b| b.likes.count <=> a.likes.count}
        @race
      end
    elsif params[:type_id]
      type = Type.find_by(:name => params[:type_id])
      @stats = type.statistics.where(:public => true)
      render 'statistics/type_statistics'
    else
      @race
      @public_stats
    end
  end

  def edit 
    @statistic = Statistic.find(params[:id])
    @race = @statistic.race
  end

  def update 
    @statistic = Statistic.find(params[:id])
    if @statistic.update(stat_params)
      redirect_to race_statistics_path(@statistic.race)
    else
      edit_statistic_path(@statistic)
    end
  end

  def destroy 
    stat = Statistic.find(params[:id])
    race = stat.race
    Like.where(:statistic_id => stat.id).each do |like|
      like.delete
    end
    stat.delete
    redirect_to race_statistics_path(race)
  end

  private 
  
  def stat_params
    params.require(:statistic).permit(:finish_time, :finish_pace, :public, :id)
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper

    def form_submit_text(statistic)
        if statistic.user_id == nil 
            "Add My Stats"
        else
            "Update My Stats"
        end
    end

    def recent_friend_statistics
        Statistic.where(:user => current_user.friends).where(:public => true).order(created_at: :desc).limit(10)
    end
    
end

app/views/statistics/_form.html.erb
<%if @statistic.user_id == nil%>
<%=form_with(model: @statistic, url: race_statistics_path(@statistic.race), method: 'post') do |f|%>
    <%=render 'form_partial', f:f%>
    <div class="button", style="padding-top:10px"><%=f.submit form_submit_text(@statistic)%></div>
    <%end%>
<%else%>
<%=form_with(model: @statistic, url: race_statistic_path(@statistic.race, @statistic), method: 'put') do |f|%>
    <%=render 'form_partial', f:f%>
    <div class="button", style="padding-top:10px"><%=f.submit form_submit_text(@statistic)%></div>
    <%end%>
<%end%> 

app/views/statistics/_form_partial.html.erb
<%=f.hidden_field :id%>
<%=f.label :finish_time, "Finish Time:"%>
<%=f.text_field :finish_time, value: finish_time_value(@race), placeholder: "hh:mm:ss", pattern: /\d{2}:[012345][0-9]:[012345][0-9]/%><br>
<%=f.label :finish_pace, "Finish Pace:"%>
<%=f.text_field :finish_pace, value: finish_pace_value(@race), placeholder: "mm:ss", pattern: "[012345][0-9]:[012345][0-9]"%><br><br>
<%=f.label :public, "Stats are public:"%>
<%=f.check_box :public%><br><br>

app/views/statistics/edit.html.erb
<div style="padding-left: 20px">
<h1>Edit Your Statistic</h1>
    <%=render '/application/errors', model:@statistic%>
    <%= render 'races/race_view'%>
    <h4 style="text-align:left">Update Your Stats</h4>
    <%=render 'form'%>
    <div class="button", style="padding-top:10px"><%=link_to "Delete My Stats", statistic_path(current_user_stats_for_form(@race)), :method => 'delete'%></div>
</div>

app/views/statistics/index.html.erb
<%= flash[:message]%>
<div class="race_stats", style="padding-left: 20px">
<h1 style="margin: 15px 0px 5px 0px"><%=@race.display_name%></h1>
<div class="race_view"></div>
<ul style="list-style-type:none;padding:0px;margin-top:10px">
    <li><div class="race_view">Location: </div><%=@race.location%></li>
    <li><div class="race_view">Date: </div><%=@race.date_format%></li>
    <li><div class="race_view">Type: </div><%=@race.type.name%></li>
</ul>
    <table class = "finisher_stats">
        <thead>
        <caption><h3 style="text-align: center;margin-top:0px">Total Finishers: <%=@race.statistics.count%></h3></caption>
            <tr>
                <th></th>
                <th id="table-name"><%=link_to "Name", race_statistics_path(@race, sort: "name")%></th>
                <th>Age</th>
                <th><%=link_to "Finish Time", race_statistics_path(@race, sort: "finish_time")%></th>
                <th>Pace</th>
                <%if logged_in?%>
                <th><%=link_to "Likes", race_statistics_path(@race, sort: "likes")%></th>
                <%end%>
            </tr>
        </thead>
        <body>
            <%x = 0%>
            <%@public_stats.each do |stat| %>  
            <tr>
                <td><%= x += 1%></td>
                <td><%=stat.user.first_name%> <%=stat.user.last_name%></td>
                <td><%=stat.user.age%></td>
                <td><%=stat.finish_time_format%></td>
                <td><%=stat.finish_pace_format%></td>
                <%if logged_in?%>
                <td><%=stat.likes.count%> <%=current_user_like_link(stat)%></td>
                <%end%>
            </tr>
            <%end%>
        </body>
    </table><br><br>

<%if @race.owner == current_user && logged_in?%>
    <div class="button"><%=link_to "Edit Race", edit_race_path(@race), method: 'get'%>
<%elsif @race.users.include?(current_user)%>
    <div class="button"><%=link_to "Edit My Statistic", edit_race_statistic_path(@race.id, current_user_stats(@race).id)%></div>
<%elsif !logged_in?%>
    <%nil%>
<%else%>
    <div class="button"><%=link_to "Add My Statistic", new_race_statistic_path(@race)%></div>
<%end%>
</div>

app/views/statistics/new.html.erb
<div style="padding-left: 20px;padding-top:10px">
    <%=render 'races/race_view'%>
    <h4 style="text-align: left">Add Your Stats</h4>
    <%=render '/application/errors', model:@statistic%>
    <%=render 'form'%>
</div>
    

app/views/statistics/type_statistics.html.erb
<h1><%=@stats.first.race.type.name%> Statistics</h1>
<ul><%=@stats.each do |stat|%>
    <li><%=stat.finish_time_format%> - <%=stat.finish_pace_format%></li>
    <%end%>
</ul>