config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#home'
  get '/users/show_race_type'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#logout'
  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
  resources :users do 
    resources :friendships, only: [:create, :show]
  end
  resources :friendships, only: [:update]
  resources :statistics, only: [:destroy] do 
      resources :likes, only: [:create]
    end
  resources :likes, only: [:update]
  resources :races, except: [:destroy] do
    resources :statistics, only: [:new, :create, :index, :edit, :update] 
  end
  resources :types do 
    resources :statistics, only: [:index]
  end
  get "/types/:slug_races", to: 'types#show_races'
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :statistics
    has_many :races, through: :statistics
    has_many :likes, through: :statistics
    has_many :types, through: :races
    has_many :friendships
    has_many :friends, through: :friendships
    validates :email, presence: true, uniqueness: true
    validates :first_name, :last_name, presence: true, format: { with: /\A\D+\z/,
        message: "cannot contain numbers" }
    validates :last_name, presence: true
    validates :password, confirmation: true, :on => :create
    validates :password_confirmation, presence: true, :on => :create, unless: Proc.new { |a| a.UID.present?}
    validates :age, numericality: { less_than: 100, greater_than: 0, message: "must be a number between 1 and 99"}, unless: Proc.new { |a| a.UID.present?}

    def self.create_from_omniauth(auth)
        user = self.find_or_create_by(UID: auth['uid'], provider: auth['provider']) do |u|
            u.email = auth['info']['email']
            u.first_name = auth['info']['first_name']
            u.last_name = auth['info']['last_name']
            u.password = SecureRandom.hex(16)
        end
    end

    def total_race_type_distance(distance)
        count = self.types.where(:name => distance).count
        if self.types.where(:name => distance).first != nil
            distance = self.types.where(:name => distance).first.distance
        else
            distance = 0
        end
        count * distance
    end

    def friends 
        users = []
        self.friendships.where(:friendship => true).each do |friendship|
            users << User.find(friendship.friend_id)
        end 
        users
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in, only: [:show, :show_race_type, :edit, :update]

    def new 
        @user = User.new 
    end

    def index 
        if params[:filter].present?
            @users = User.where("first_name ~* ? or last_name ~* ?", "#{params[:filter]}", "#{params[:filter]}")
            @friends = current_user.friends.sort_by{|friend|friend.last_name}
        else
            @users = User.where("id NOT IN(?)", current_user.id).order(:last_name)
            @friends = current_user.friends.sort_by{|friend|friend.last_name}
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def edit 
        @user = current_user
    end

    def update 
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:message] = "Successfully Saved!"
            redirect_to edit_user_path(@user)
        else
            render :edit 
        end
    end

    def show 
        @user = User.find(params[:id])
        if @user == current_user
            'show'
        else
            redirect_to '/'
        end
    end

    def show_race_type
        @type = Type.find(params[:format])
    end

    private 

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :age, :password, :password_confirmation, :filter)
    end
end

app/helpers/users_helper.rb
module UsersHelper
    
    def dashboard
    ["5k", "10k", "Half-Marathon", "Marathon"]
    end

    def find_type(type)
        Type.find_by(:name => type)
    end

    def user_race_count_of_type(type)
        current_user.races.where(:type => user_races_of_type(type)).count
    end

    def user_races_of_type(type)
        if current_user.types.where(:name => type) != []
            current_user.types.where(:name => type).first
        else
            []
        end
    end

    def fastest_race_finish_time(type)
        if user_races_of_type(type) != []
            "Finish Time: " + user_races_of_type(type).statistics.ordered.where(:user => current_user).first.finish_time_format
        else 
            ""
        end
    end

    def fastest_race_finish_pace(type)
        if user_races_of_type(type) != []
            "Finish Pace: " + user_races_of_type(type).statistics.ordered.where(:user => current_user).first.finish_pace_format
        else 
            ""
        end
    end

    def fastest_race_name(type)
        if user_races_of_type(type) != []
            user_races_of_type(type).statistics.ordered.where(:user => current_user).first.race.name
        else 
            "Not Yet Available"
        end
    end

    def fastest_race_year(type)
        if user_races_of_type(type) != []
            user_races_of_type(type).statistics.ordered.where(:user => current_user).first.race.date.strftime("%Y")
        else 
            ""
        end
    end



    
end

app/views/users/_dashboard.html.erb
<div class="dashboard", style="border-radius:25px">
    <div id="dashboard"><h2>My Racing Dashboard</h2></div>
    <div id="race_types" style="padding:8px;grid-gap:8px;background-color:white">
        <%dashboard.each do |type|%>
            <div id=<%=type%> style="padding:5px;border:3px solid;border-color:rgb(65, 130, 187);border-radius:5px;background-color:white;height:270px;width:220px"><h4 style="margin-top:1.5px"><%=link_to type, type_path(find_type(type))%></h4>
                <ul>
                <li style="font-weight:bold">Finished</li>
                <li><%=user_race_count_of_type(type)%></li><br>
                <li style="font-weight:bold">Total Miles</li>
                <li><%=current_user.total_race_type_distance(type)%></li><br>
                    <div class="fastest">
                    <li style="font-weight:bold">Fastest <%=type%></li>
                    <li><%=fastest_race_name(type)%></li>
                    <li><%=fastest_race_year(type)%></li>
                    <li><%=fastest_race_finish_time(type)%></li>
                    <li><%=fastest_race_finish_pace(type)%></li>
                    </div>
                </ul>
            </div>  
        <%end%>                   
    </div>
</div>

app/views/users/_form.html.erb
<div class="user_form">
<%= form_with(model: @user) do |f|%>
    <%=f.label :first_name, "First Name:"%>
    <%=f.text_field :first_name%><br>
    <%=f.label :last_name, "Last Name:"%>
    <%=f.text_field :last_name%><br>
    <%=f.label :email, "Email:"%>
    <%=f.email_field :email%><br>
    <%=f.label :age, "Age:"%>
    <%=f.number_field :age%><br>
    <%=f.label :password, "Password:"%>
    <%=f.password_field :password%><br>
    <%=f.label :password_confirmation, "Confirm Password:"%>
    <%=f.password_field :password_confirmation%><br>
    <div class="button", style="padding-top:20px"><%=f.submit "Create My Profile"%></div>
    <%end%>
</div>

app/views/users/_friends_table.html.erb
<table class="friends_table">
        <thead>
        <caption></caption>
            <tr>
                <th>Name</th>
                <th>Race</th>
                <th>Date</th>
                <th>Finish Time</th>
                <th>Likes</th>
            </tr>
        </thead>
        <body>
            <%recent_friend_statistics.each do |stat|%>
            <tr>
                <td><%=stat.user.first_name%> <%=stat.user.last_name%></td>
                <td><%=link_to stat.race.display_name, race_statistics_path(stat.race), style: "text-decoration:none"%></td>
                <td><%=stat.race.date.strftime("%b %d")%></td>
                <td><%=stat.finish_time_format%></td>
                <td><%=stat.likes.count%> <%=like_link_from_dashboard(stat)%></td>
            </tr>
            <%end%>
        </body>
    </table>

app/views/users/edit.html.erb
<div style="padding-left: 20px">
<%= flash[:message]%>
<h1>My Profile</h1>
    <%=render '/application/errors', model:@user%>  
    <%= form_with(model: @user) do |f|%>
        <%=f.label :first_name, "First Name:"%>
        <%=f.text_field :first_name%><br>
        <%=f.label :last_name, "Last Name:"%>
        <%=f.text_field :last_name%><br>
        <%=f.label :email, "Email:"%>
        <%=f.email_field :email%><br>
        <%=f.label :age, "Age:"%>
        <%=f.number_field :age%><br>
        <div class="button", style="padding-top:20px"><%=f.submit "Update My Profile"%></div>
    <%end%>
</div>

app/views/users/index.html.erb
<div class="runners", style="padding-left: 30px">
    <div class="two", style="block:inline">
    <h1 style="margin-bottom:0px">All Runners</h1>
    <br>
    <%= form_tag(users_path, method:"get") do |f| %>
            <%= text_field_tag('filter', nil, placeholder: "Search by Name", style: "display:-webkit-inline-flex") %>
            <div class="button", style="padding-top:20px"><%= submit_tag("Find")%></div>
        <% end %>

    <table class="finisher_stats">
        <thead>
            <tr>
                <th>Last Name</th>
                <th>First Name</th>
                <th>Age</th>
                <th>Follow</th>
            </tr> 
        </thead>
        <body>
            <tr>
                <%@users.each do |user|%>
                <td><%=user.last_name%> </td>
                <td><%=user.first_name%></td>
                <td><%=user.age%></td>
                <td><%=friend_link(user)%></td>
            </tr>
                <%end%>
        </body>
    </table>
    </div>

    <div class="one">
        <h1 style="margin-bottom:0px">Tracking</h1>
        <%@friends.each do |friend|%>
            <p style="margin-left:10px"><%=link_to "#{friend.first_name} #{friend.last_name}", user_friendship_path(current_user, friend)%></p>
        <%end%>
    </div>
</div>

app/views/users/new.html.erb
<div class="header", style="padding-left:20px">
  <h1>Create Profile</h1>
  <%=render '/application/errors', model:@user%>
  <%= render 'form'%>
</div>

app/views/users/show.html.erb
 
 
 <div style="padding:20px;background-color:rgb(65, 130, 187)"><%= flash[:message]%></div>

<div class="row", style="padding:10px;background-color:rgb(65, 130, 187)">
    <%if @races%>
        <%= render 'users/dashboard'%>
    <%else%>
        <%=render 'dashboard'%>
    <%end%>
    <div class="column_two">
        <div class="race_search">
        <h2 style="text-align:center">Find or Create A Race</h2><br>
        <%= form_tag(races_path, method:"get") do |f| %>
            <%= label_tag("Search by:", nil, style:"width: 100px") %>
            <%= text_field_tag('filter', nil, placeholder: "Name/City/Location", style: "display:-webkit-inline-flex") %>
            <div style="padding:5px">and/or</div>
            <%= label_tag("date:", nil, style:"width: 80px") %>
            <%= date_field_tag('date') %>
            <div class="button", style="padding-top:20px"><%= submit_tag("Search")%> <%=link_to "New Race", new_race_path%></div>
            <div class="button", style="padding-top:20;"></div><br>
        <% end %>
            <%=flash[:race]%>
        <%if @races%>
            <%=render '/races/public_races'%>
        <%end%>
        </div>
        <div class="friends">
            <h2 style="text-align:center;border-top-radius:0px">Tracking Feed</h2><br>
            <%if @races%>
                <%=render 'users/friends_table'%>
            <%else%>
                <%=render 'friends_table'%>
            <%end%>
        </div>
    </div>
</div>

app/views/users/show_race_type.html.erb
<div style="padding-left: 20px">
<h1>My <%=@type.name%>s</h1>
    <p>
    <table class = "finisher_stats">
        <thead>
        <caption><h3 style="text-align: center"></h3></caption>
            <tr>
                <th></th>
                <th><%=link_to "Race", type_path(@type, sort: "name")%></th>
                <th><%=link_to "Location", type_path(@type, sort: "location")%></th>
                <th><%=link_to "Date", type_path(@type, sort: "date")%></th>
                <th><%=link_to "Finish Time", type_path(@type, sort: "finish_time")%></th>
                <th>Pace</th>
                <th><%=link_to "Likes", type_path(@type, sort: "likes")%></th>
            </tr>
        </thead>
        <body>
            <%@my_stats.each_with_index do |stat, index|%>
            <tr>
                <td><%=index + 1%></td>
                <td><%=link_to stat.race.display_name, race_statistics_path(stat.race), style: "text-decoration:none"%></td>
                <td><%=stat.race.location%></td>
                <td><%=stat.race.date_format%></td>
                <td><%=current_user_stats(stat.race).finish_time_format%></td>
                <td><%=current_user_stats(stat.race).finish_pace_format%></td>
                <td><%=stat.likes.count%> <%=current_user_like_link(stat)%></td>
            </tr>
            <%end%>
        </body>
    </table>
    </p>
</div>